### ISSUE TITLE
Mensagem de criação de fatura fixa antes da aprovação dos itens

### ISSUE THREAD

**Issue by rmfalcao** [rmfalcao/sisjuf-repositorio#13]
Ao clicar em salvar a fatura (gerar fatura) aparece o modal "aprovar os itens da fatura", porém a tela atrás já exibe a mensagem "Fatura Prévia gerada com sucesso", não deveria ser depois do usuário apertar SALVAR na tela de itens de fatura? Essa funcionalidade "aprovar itens da fatura" não existia, achei até interessante quando vocês colocaram mas neste caso deveria esperar o usuário confirmar para salvar.

**Comment by afamorim** [comment]
feito
