### ISSUE TITLE
Datas da fatura no banco divergem da tela

### ISSUE THREAD

**Issue by rmfalcao** [rmfalcao/sisjuf-repositorio#14]
Gerei uma fatura vitalmed data inicio 01/06/2015 e data fim 30/06/2015, vi que no banco os valores foram gravados corretamente, mas a tela de detalhamento da fatura está mostrando data inicio 31/05/2015 e data fim 29/06/2015. Vocês poderiam verificar? Dei uma olhada nas classes de negócio e aparemente elas não alteram os valores dessas datas, simplesmente pesquisam como vêm do banco e colocam nos objetos

**Comment by afamorim** [comment]
Diguinho como mostra as imagens abaixo, na minha máquina estão ok. Poderia simular em homologação, pois não pude validar

![image](https://cloud.githubusercontent.com/assets/3629577/8948241/56e5212e-357b-11e5-9ae6-eded7aaf3003.png)

![image](https://cloud.githubusercontent.com/assets/3629577/8948251/852205d4-357b-11e5-8024-6c2a4a118359.png)
