### ISSUE TITLE
Tela de upload da fatura fixa desformatada

### ISSUE THREAD

**Issue by rmfalcao** [rmfalcao/sisjuf-repositorio#15]
A tela de upload do arquivo da fatura está com um problema de layout, estou abrindo no firefox do Mac e o modal aparece desformatado (ver espaço que "sobra" do lado direito do modal), não sei se fica assim no Windows. Ver no anexo como aparece em minha máquina.

![captura de tela 2015-07-28 22 28 37](https://cloud.githubusercontent.com/assets/2186374/8942879/26703b4e-3578-11e5-8f7d-5c589ccd374d.png)

**Comment by afamorim** [comment]
comitado
