### ISSUE TITLE
Navegação após gerar fatura com sucesso

### ISSUE THREAD

**Issue by rmfalcao** [rmfalcao/sisjuf-repositorio#16]
apos gravar fatura (previa gerada com sucesso) deveria ir pra tela de detalhamento da fatura (que exibe o codigo da fatura gerada e da as opcoes de validar/cancelar).

**Comment by afamorim** [comment]
Porque pemanece aberta essa issue diguinho? Vc viu algum problema?

**Comment by rmfalcao** [comment]
conferi agora e está OK!
