### ISSUE TITLE
Falha ao inserir mais de 1 item em fatura variável

### ISSUE THREAD

**Issue by rmfalcao** [rmfalcao/sisjuf-repositorio#17]
Ao clicar no botão NOVO de inserir item de fatura variável, após salvar o primeiro item o modal permanece aberto e é limpado para o usuário digitar o próximo item, caso deseje (este comportamento está correto), entretanto a partir da inserção do segundo item de fatura, ele é salvo na lista da tela principal sem o preenchimento da coluna TITULAR, e aí na hora de salvar dá erro.

**Comment by afamorim** [comment]
feito

**Comment by rmfalcao** [comment]
Não funcionou, segue print do teste realizado
![captura de tela 2015-07-30 22 16 14](https://cloud.githubusercontent.com/assets/2186374/8993955/a34c66ce-3708-11e5-8d61-34f3c1d88f7f.png)

**Comment by afamorim** [comment]
Rodrigo, existe algum problema no momento de adicionar um beneficiario. Entendendo o código, o sistema no momento que adiciona procura buscar um beneficiário e no momento em que vai salva a fatura ele busca o  numero de vinculação, que não existe uma vez que ele não localiza o beneficiário no momento em que se adiciona o mesmo.

Então tem que verificar a regra de negócio, pois um convênio variável não faz sentido adicionar um beneficiário, tinha que ser um associado e no momento de salvar esse tipo de fatura não devia buscar o número de vinculação que não existe, mas sim o código do associado. Por favor confirme isso, para se fazer a atuação correta sobre o código.

**Comment by rmfalcao** [comment]
@afamorim ,

Quem a gente vincula ao item da fatura é sempre o beneficiario, nesse sentido está correto o que o sistema está tentando fazer: o usuário do convênio pode ser o titular ou não, então é o nome do beneficiário quem deve ir mesmo. Do ponto de vista do modelo de DADOS, a tabela ITEM_FATURA tem uma coluna "SEQ_VINCULACAO_PLANO", através da qual se sabe quem é o beneficiário e, consequentemente, o titular.

FIZ MAIS ALGUNS TESTES e identifiquei um padrão de como simular o problema e como fazer com que o problema não aconteça: o problema só acontece quando tentamos adicionar os itens da fatura sem fechar o modal (o que é desejável, por ser mais prático - sempre que salvamos um item, a tela é limpada para podermos adicionar o próximo). Se, porém, o usuário fechar o modal a cada item adicionado e abrir de novo para adicionar o novo item, funciona lindamente. Ou seja, acredito que o problema é alguma variável que esteja se "perdendo" quando deixamos o modal aberto e tentamos inserir o próximo item!

**Comment by afamorim** [comment]
A questão de tela foi resolvida, no entanto em regra de negócio ainda estou erro de data que não está presente em tela.
