### ISSUE TITLE
Erro link "Baixar Fatura" no grid de faturas da tela de Pesquisa de Fatura

### ISSUE THREAD

**Issue by rmfalcao** [rmfalcao/sisjuf-repositorio#22]
pesquisa de faturas so deveria apresentar os links para baixar fatura (última coluna) no caso da fatura estar no status "validada" e com flag "nao paga". Em qualquer outra situação, o link não deve aparecer.

ainda sobre o link baixar faturas supracitado: ao clicar nele já abre a tela preenchendo previamento vários campos do lançamento (correto!) mas um campo está vindo errado: o TIPO OPERACAO deve ser DÉBITO, e não "a debitar".

**Comment by rmfalcao** [comment]
Em vez do link "baixar fatura", usar o ícone que já é empregado na consulta de lançamentos para representar a mesma ação ("baixar fatura"), é o antepenúltimo link abaixo ilustrado.

![captura de tela 2015-08-09 21 57 49](https://cloud.githubusercontent.com/assets/2186374/9156660/df2de150-3ee1-11e5-99de-1dbd17c1cfba.png)

**Comment by afamorim** [comment]
Tem que gerar o teste de novo do baixa fatura, pois como tinha sido salvo o lançamento a debitar caso use o mesmo sem modificar o registro do banco o mesmo dará nullpointer.
