### ISSUE TITLE
ação imprimir na aba beneficiários com falha de permissão

### ISSUE THREAD

**Issue by rmfalcao** [rmfalcao/sisjuf-repositorio#24]
Testei com usuário admin a função de impressão da lista de beneficiários da aba BENEFICIÁRIOS da tela de Detalhamento de Convenio. Provavelmente falta configurar a URL na segurança.

![captura de tela 2015-08-12 21 04 52](https://cloud.githubusercontent.com/assets/2186374/9233995/92c199d6-4136-11e5-97cf-a6b845ec8925.png)

**Comment by afamorim** [comment]
INSERT INTO LINK_FUNCAO (SEQ_LINK, URL, DESCRICAO, TIPO) VALUES (nextval('SEQ_LINK'), '/associados/convenio/BeneficiarioImpressao', 'Imprimir Beneficiario', 1);

INSERT INTO FUNCAO (SEQ_FUNCAO, SEQ_LINK, NOME, DESCRICAO) VALUES (nextval('SEQ_FUNCAO'), (select SEQ_LINK from LINK_FUNCAO where URL like '/associados/convenio/BeneficiarioImpressao'), 'Imprimir Beneficiario', 'Imprimir Beneficiario');

INSERT INTO FUNCIONALIDADE (SEQ_FUNCIONALIDADE, NOME, DESCRICAO) VALUES (nextval('SEQ_FUNCIONALIDADE'), 'Imprimir Beneficiario', 'Imprimir Beneficiario');

insert into funcao_funcionalidade (seq_funcao, seq_funcionalidade) values ((select seq_funcao from funcao where nome = 'Imprimir Beneficiario'), (select seq_funcionalidade from funcionalidade where nome = 'Imprimir Beneficiario'));
